/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CacheOptions {
  maxMemory?: number
  maxItems?: number
  checkPeriod?: number
}
export interface CacheStats {
  memoryUsage: number
  maxItems: number
  memoryUsed: number
  hits: number
  misses: number
}
export interface CacheEntry {
  value: string
  size: number
  priority: number
  createdAt: number
  expiresAt?: number
}
export declare function createMemoryUnits(): MemoryUnits
export declare class MemoryUnits {
  b: number
  kb: number
  mb: number
  gb: number
}
export declare class MussuranaCache {
  constructor(options?: CacheOptions | undefined | null)
  set(key: string, value: string, ttl?: number | undefined | null, priority?: number | undefined | null): boolean
  get(key: string): string | null
  delete(key: string): boolean
  getStats(): CacheStats
  clear(): void
}
