name: CI

env:
  CARGO_TERM_COLOR: always
  APP_NAME: mussurana_cache

on:
  push:
    branches: [main]
    paths-ignore:
        - '**/*.md'
        - 'docs/**'
        - '**/*.png'
  pull_request:
      branches: [main]

jobs:
  build:
    name: Build ${{ matrix.config.target }}
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
          config:
              - {
                  os: ubuntu-latest,
                  target: x86_64-unknown-linux-gnu,
                  cross: false
              }
              - {
                  os: windows-latest,
                  target: x86_64-pc-windows-msvc,
                  cross: false
              }
              - {
                  os: macos-latest,
                  target: x86_64-apple-darwin,
                  cross: false
                }
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.config.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential

      - name: Setup yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: latest

      - name: Install npm dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          RUST_BACKTRACE: 1

      - name: Test
        run: yarn test
